# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/stud2021/1kolanko/JOS/lab2/lab2/lab2.srcs/sources_1/ip/ila_scope/ila_scope.xci
# IP: The module: 'ila_scope' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stud2021/1kolanko/JOS/lab2/lab2/lab2.gen/sources_1/ip/ila_scope/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_scope'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/stud2021/1kolanko/JOS/lab2/lab2/lab2.gen/sources_1/ip/ila_scope/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_scope'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/stud2021/1kolanko/JOS/lab2/lab2/lab2.gen/sources_1/ip/ila_scope/ila_scope_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_scope'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/stud2021/1kolanko/JOS/lab2/lab2/lab2.srcs/sources_1/ip/ila_scope/ila_scope.xci
# IP: The module: 'ila_scope' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stud2021/1kolanko/JOS/lab2/lab2/lab2.gen/sources_1/ip/ila_scope/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_scope'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/stud2021/1kolanko/JOS/lab2/lab2/lab2.gen/sources_1/ip/ila_scope/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_scope'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/stud2021/1kolanko/JOS/lab2/lab2/lab2.gen/sources_1/ip/ila_scope/ila_scope_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_scope'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
