# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/stud2021/1kolanko/JOS/JOS_old_V/JOS_old_V.srcs/sources_1/ip/axi_uartlite_0_1/axi_uartlite_0.xci
# IP: The module: 'axi_uartlite_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stud2021/1kolanko/JOS/JOS_old_V/JOS_old_V.gen/sources_1/ip/axi_uartlite_0_1/axi_uartlite_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/stud2021/1kolanko/JOS/JOS_old_V/JOS_old_V.gen/sources_1/ip/axi_uartlite_0_1/axi_uartlite_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/stud2021/1kolanko/JOS/JOS_old_V/JOS_old_V.gen/sources_1/ip/axi_uartlite_0_1/axi_uartlite_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/stud2021/1kolanko/JOS/JOS_old_V/JOS_old_V.srcs/sources_1/ip/axi_uartlite_0_1/axi_uartlite_0.xci
# IP: The module: 'axi_uartlite_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/stud2021/1kolanko/JOS/JOS_old_V/JOS_old_V.gen/sources_1/ip/axi_uartlite_0_1/axi_uartlite_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/stud2021/1kolanko/JOS/JOS_old_V/JOS_old_V.gen/sources_1/ip/axi_uartlite_0_1/axi_uartlite_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/stud2021/1kolanko/JOS/JOS_old_V/JOS_old_V.gen/sources_1/ip/axi_uartlite_0_1/axi_uartlite_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_uartlite_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
